src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GTV_Account_Category__c</fullName>
        <label>Gotransverse Account Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTV_Bill_Cycle__c</fullName>
        <label>Gotransverse Bill Cycle</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTV_Payment_Term__c</fullName>
        <label>Gotransverse Payment Term</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tract_Billing_Account__c</fullName>
        <label>Gotransverse Billing Account #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/Payment_Term__c.object
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRACT_Bill_Cycle__c.object
<CustomObject>
    <label>Gotransverse Bill Cycle</label>
    <nameField>
        <label>Gotransverse Bill Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gotransverse Bill Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/TRACT_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to save the Gotransverse Configuration details.</description>
    <label>Gotransverse Setup</label>
</CustomObject>

src/objects/TRACTBillingAccountCategory__c.object
<CustomObject>
    <label>GotransverseBillingAccountCategory</label>
    <nameField>
        <label>GotransverseBillingAccountCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GotransverseBillingAccountCategorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TabbedAccount_LtController_Test.cls
/**
 * Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
 * This software contains confidential and trade secret information of:
 * Transverse, LLC.
 * 620 Congress Ave.
 * Suite 200
 * Austin, TX 78701
 * USA
 * Use, duplication or disclosure of this software is prohibited
 * without prior written permission of Transverse, LLC.
 */

/**
 * This class is a test class of TabbedAccount_LtController class.
 * @author Aman Jain
 */

@isTest
public class TabbedAccount_LtController_Test {
  static testMethod void myunitTest() {
    Account acc = HelperClass.getAccount();
    insert acc;

    TRACT_Setup__c tractSetup = HelperClass.getTract();
    insert tractSetup;

    TRACTBillingAccountCategory__c tractBilling = HelperClass.getAccountCategory();
    insert tractBilling;

    TRACT_Bill_Cycle__c billcycle = HelperClass.getBillCycle();
    insert billcycle;

    Payment_Term__c paymentTerms = HelperClass.getPaymentTerms();
    insert paymentTerms;

    Test.startTest();
    tabbedAccount_LtController.checkBilingAccount(acc.id);
    tabbedAccount_LtController.saveAccount(acc.id);
    Test.stopTest();

    System.assertNotEquals(acc, null);
  }

  static testMethod void myunitTestTwo() {
    Account acc = HelperClass.getAccount();
    insert acc;

    TRACT_Setup__c tractSetup = HelperClass.getAPI2TRACT();
    insert tractSetup;

    TRACTBillingAccountCategory__c tractBilling = HelperClass.getAccountCategory();
    insert tractBilling;

    TRACT_Bill_Cycle__c billcycle = HelperClass.getBillCycle();
    insert billcycle;

    Payment_Term__c paymentTerms = HelperClass.getPaymentTerms();
    insert paymentTerms;

    Test.startTest();
    tabbedAccount_LtController.checkBilingAccount(acc.id);
    tabbedAccount_LtController.saveAccount(acc.id);
    // GlobalGTVActions.createBillingAccount(acc.id);
    Test.stopTest();

    System.assertNotEquals(acc, null);
  }

  static testMethod void myunitTest3() {
    Account acc = HelperClass.getAccount();
    insert acc;

    TRACT_Setup__c tractSetup = HelperClass.getAPI1TRACT();
    insert tractSetup;

    TRACTBillingAccountCategory__c tractBilling = HelperClass.getAccountCategory();
    insert tractBilling;

    TRACT_Bill_Cycle__c billcycle = HelperClass.getBillCycle();
    insert billcycle;

    Payment_Term__c paymentTerms = HelperClass.getPaymentTerms();
    insert paymentTerms;

    Test.startTest();
    tabbedAccount_LtController.checkBilingAccount(acc.id);
    tabbedAccount_LtController.saveAccount(acc.id);
    //GlobalGTVActions.createBillingAccount(acc.id);
    Test.stopTest();

    System.assertNotEquals(acc, null);
  }
  static testMethod void myunitTest4() {
    Account acc = HelperClass.getAccount();
    acc.Tract_Billing_Account__c = null;
    acc.GTV_Account_Category__c = 'testType';
    acc.GTV_Payment_Term__c = 'Net 30';
    acc.GTV_Bill_Cycle__c = 'testBill';
    insert acc;

    TRACT_Setup__c tractSetup = HelperClass.getAPI1TRACT();
    insert tractSetup;

    TRACTBillingAccountCategory__c tractBilling = HelperClass.getAccountCategory();
    insert tractBilling;

    TRACT_Bill_Cycle__c billcycle = HelperClass.getBillCycle();
    insert billcycle;

    Payment_Term__c paymentTerms = HelperClass.getPaymentTerms();
    insert paymentTerms;

    Test.startTest();
    tabbedAccount_LtController.checkBilingAccount(acc.id);
    tabbedAccount_LtController.saveAccount(acc.id);
    //GlobalGTVActions.createBillingAccount(acc.id);
    Test.stopTest();

    System.assertNotEquals(acc, null);
  }
  static testMethod void myunitTest5() {
    Account acc = HelperClass.getAccount();
    acc.GTV_Account_Category__c = 'testType';
    acc.GTV_Payment_Term__c = 'Net 30';
    acc.GTV_Bill_Cycle__c = 'testBill';
    acc.Tract_Billing_Account__c = '123';
    insert acc;

    TRACT_Setup__c tractSetup = HelperClass.getAPI2TRACT();
    insert tractSetup;

    TRACTBillingAccountCategory__c tractBilling = HelperClass.getAccountCategory();
    insert tractBilling;

    TRACT_Bill_Cycle__c billcycle = HelperClass.getBillCycle();
    insert billcycle;

    Payment_Term__c paymentTerms = HelperClass.getPaymentTerms();
    insert paymentTerms;

    Test.startTest();
    tabbedAccount_LtController.checkBilingAccount(acc.id);
    tabbedAccount_LtController.saveAccount(acc.id);
    //GlobalGTVActions.createBillingAccount(acc.id);
    Test.stopTest();

    System.assertNotEquals(acc, null);
  }
}