src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Gotransverse Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Please enter an email for the responsible person, to represent the tenant.</inlineHelpText>
        <label>Gotransverse Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OneTimePrice__c</fullName>
        <label>Gotransverse OneTimePrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RecurringPrice__c</fullName>
        <label>Gotransverse RecurringPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gotransverse Service Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Service_Resource__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Please select an active Service Resource</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Resource__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <description>Please enter a unique user name.</description>
        <inlineHelpText>Please enter a unique user name for the responsible person, to represent the tenant.</inlineHelpText>
        <label>Gotransverse User name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceOverride__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Gotransverse Price Override</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Service_Resource__c.object
<CustomObject>
    <description>TRACT Service Resource is required for Products.</description>
    <label>Service Resource</label>
    <nameField>
        <label>Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/TRACT_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to save the Gotransverse Configuration details.</description>
    <label>Gotransverse Setup</label>
    <fields>
        <fullName>Api_Version__c</fullName>
        <label>Gotransverse Api Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TRACTSetUp_Test.cls
/**
 * Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
 * This software contains confidential and trade secret information of:
 * Transverse, LLC.
 * 620 Congress Ave.
 * Suite 200
 * Austin, TX 78701
 * USA
 * Use, duplication or disclosure of this software is prohibited
 * without prior written permission of Transverse, LLC.
 */

/**
 * This class is a test class of TRACTSetUp class.
 * @author Aman Jain
 */

@isTest
private class TRACTSetUp_Test {
  static testMethod void myUnitTest() {
    // TO DO: implement unit test
    TRACT_Setup__c tract = HelperClass.getTract();
    tract.Api_Version__c = '30';
    System.assert(tract != null);
    insert tract;

    Account account = HelperClass.getAccount();
    insert account;

    List<Account> thisAccountList = new List<Account>();
    thisAccountList.add(account);

    Opportunity opportunity = HelperClass.getOpportunity();
    opportunity.AccountId = account.Id;
    System.assert(opportunity != null);
    insert opportunity;

    List<Opportunity> thisOppList = new List<Opportunity>();
    thisOppList.add(opportunity);

    Service_Resource__c serviceresource = HelperClass.getServiceresource();
    insert serviceresource;

    Pricebook2 pricebook = HelperClass.getPriceBook2();
    insert pricebook;

    Product2 product = (Product2) SmartFactory.createSObject('Product2');
    product.name = 'product';
    product.eid__c = '12345';
    product.ProductCode = 'SUBSCRIPTION';
    product.IsActive = true;
    //product.ReccPriceOverride__c = true;
    product.PriceOverride__c = true;
    system.assert(product != null);
    insert product;

    Id pricebookId = Test.getStandardPricebookId();

    PricebookEntry pricebookEntryObj = (PricebookEntry) SmartFactory.createSObject(
      'PricebookEntry'
    );
    pricebookEntryObj.Pricebook2Id = pricebookId;
    pricebookEntryObj.Product2Id = product.Id;
    insert pricebookEntryObj;

    PricebookEntry pricebookEntryObj1 = (PricebookEntry) SmartFactory.createSObject(
      'PricebookEntry'
    );
    pricebookEntryObj1.Pricebook2Id = pricebook.id;
    pricebookEntryObj1.Product2Id = product.Id;
    pricebookEntryObj1.UnitPrice = 10000;
    pricebookEntryObj1.IsActive = true;
    system.assert(pricebookEntryObj1 != null);
    insert pricebookEntryObj1;

    OpportunityLineItem opportunityLineItemObj = (OpportunityLineItem) SmartFactory.createSObject(
      'OpportunityLineItem'
    );
    opportunityLineItemObj.PricebookEntryId = pricebookEntryobj1.id;
    opportunityLineItemObj.TotalPrice = 2000;
    opportunityLineItemObj.Quantity = 2;
    opportunityLineItemObj.eid__c = '12345';
    opportunityLineItemObj.username__c = 'user';
    opportunityLineItemObj.Email__c = 'ravi.6380@yahoo.com';
    opportunityLineItemObj.RecurringPrice__c = 100;
    opportunityLineItemObj.OneTimePrice__c = 500;
    opportunityLineItemObj.Service_Resource__c = serviceresource.Id;
    opportunityLineItemObj.OpportunityId = opportunity.Id;
    insert opportunityLineItemObj;

    TRACTSetUp.saveServiceResource();
    TRACTSetUp.saveServiceResource();
    TRACTSetUp.savePriceBook();

    TRACTSetUp.setupPriceBookNew(tract);
    TRACTSetUp.saveSalesOrder(opportunity.Id);
  }
}