src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Create_Date__c</fullName>
        <description>This field is used to support backdating of account from Salesforce to TRACT.</description>
        <label>Gotransverse Create Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Currency_Type__c</fullName>
        <description>The Currency of the Billing Account.</description>
        <label>Gotransverse Currency Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Gotransverse Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>This field is used to show error message while making API callout to move Salesforce Account to TRACT db</description>
        <label>Gotransverse Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Gotransverse_Bill_Type__c</fullName>
        <label>Gotransverse Bill Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTV_Account_Category__c</fullName>
        <label>Gotransverse Account Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTV_Bill_Cycle__c</fullName>
        <label>Gotransverse Bill Cycle</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTV_Payment_Term__c</fullName>
        <label>Gotransverse Payment Term</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Not Moved&apos;</defaultValue>
        <label>Gotransverse Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Moved</fullName>
                </value>
                <value>
                    <fullName>Not Moved</fullName>
                </value>
                <value>
                    <fullName>Error Occurred</fullName>
                    <label>Errored</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gotransverse Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tract_Billing_Account__c</fullName>
        <label>Gotransverse Billing Account #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/Payment_Term__c.object
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/TRACT_Bill_Cycle__c.object
<CustomObject>
    <label>Gotransverse Bill Cycle</label>
    <nameField>
        <label>Gotransverse Bill Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gotransverse Bill Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Bill_Cycle_Type__c</fullName>
        <label>Gotransverse Bill Cycle Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRACT_Bill_Cycle_Currency_Type__c</fullName>
        <label>Gotransverse Bill Cycle Currency Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/TRACT_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to save the Gotransverse Configuration details.</description>
    <label>Gotransverse Setup</label>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Gotransverse Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapped_Custom_Field_Id__c</fullName>
        <description>This field store the id of custom field selected by the user on billing tab.</description>
        <label>Mapped Custom Field Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPassword__c</fullName>
        <label>Gotransverse TPassword</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRACT_URL__c</fullName>
        <defaultValue>&quot;https://tract-qa.gotransverse.com&quot;</defaultValue>
        <description>TRACT Server URL</description>
        <inlineHelpText>Please provide a correct TRACT URL. Ex https://my.tractbilling.com</inlineHelpText>
        <label>Gotransverse URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tract_User_Name__c</fullName>
        <defaultValue>&quot;algo-sales&quot;</defaultValue>
        <label>Gotransverse User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/TRACTBillingAccountCategory__c.object
<CustomObject>
    <label>GotransverseBillingAccountCategory</label>
    <nameField>
        <label>GotransverseBillingAccountCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GotransverseBillingAccountCategorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Gotransverse Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type_x__c</fullName>
        <label>Gotransverse Type_x</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TabbedAccount_LtController.cls
/**
 * Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
 * This software contains confidential and trade secret information of:
 * Transverse, LLC.
 * 620 Congress Ave.
 * Suite 200
 * Austin, TX 78701
 * USA
 * Use, duplication or disclosure of this software is prohibited
 * without prior written permission of Transverse, LLC.
 */

/**
 * This class is used to call the API request to create a billing account from Salesforce to GTV.
 * @author AMAN JAIN
 */

public class TabbedAccount_LtController {
  /**
   *Method to check for billing account.
   *@param accountId
   *@return accountId
   */
  @AuraEnabled
  public static Account checkBilingAccount(string accountId) {
    Account thisAccount = [
      SELECT
        Id,
        Name,
        BillingStreet,
        BillingCity,
        BillingPostalCode,
        BillingState,
        BillingCountry,
        AccountNumber,
        ShippingStreet,
        ShippingCity,
        ShippingPostalCode,
        ShippingState,
        ShippingCountry,
        Description,
        Phone,
        NumberOfEmployees,
        Tract_Billing_Account__c,
        Email__c,
        Account_Create_Date__c,
        Currency_Type__c,
        Tax_Exempt__c
      FROM Account
      WHERE id = :accountId
      LIMIT 1
    ];
    return thisAccount;
  }
  /**
   *Method to save account after configuration.
   *@param accountId salesforce account ID
   *@return error message
   */
  @AuraEnabled
  public static string saveAccount(string accountId) {
    string error = 'NoError';
    list<TRACT_Setup__c> tractList = new List<TRACT_Setup__c>();
    tractList = [
      SELECT
        id,
        TPassword__c,
        Tract_User_Name__c,
        TRACT_URL__c,
        Mapped_Custom_Field_Id__c,
        Active__c
      FROM TRACT_Setup__c
      WHERE Active__c = TRUE
      LIMIT 1
    ];
    TRACT_Setup__c tract = new TRACT_Setup__c();
    if (tractList.size() > 0) {
      tract = tractList[0];
    }
    list<Account> thisAccountList = [
      SELECT
        Id,
        Name,
        BillingStreet,
        BillingCity,
        GTV_Bill_Cycle__c,
        BillingPostalCode,
        BillingState,
        BillingCountry,
        AccountNumber,
        ShippingStreet,
        ShippingCity,
        ShippingPostalCode,
        ShippingState,
        ShippingCountry,
        Description,
        Phone,
        NumberOfEmployees,
        Tract_Billing_Account__c,
        Email__c,
        GTV_Payment_Term__c,
        Account_Create_Date__c,
        GTV_Account_Category__c,
        Currency_Type__c,
        Tax_Exempt__c,
        Error_Message__c,
        Status__c,
        Gotransverse_Bill_Type__c
      FROM Account
      WHERE id = :accountId
      LIMIT 1
    ];
    Account thisAccount = thisAccountList[0];
    TRACTBillingAccountCategory__c bAC;
    List<TRACTBillingAccountCategory__c> bACList = [
      SELECT id, eid__c, type_x__c
      FROM TRACTBillingAccountCategory__c
      WHERE type_x__c = :thisAccount.GTV_Account_Category__c
      LIMIT 1
    ];
    if (bACList.size() > 0) {
      bAC = bACList[0];
    } else {
      error = 'Please select the Billing Account Category.';
      return error;
    }
    string bACEid = bAC.eid__c;
    string paymentTerm;
    map<String, Payment_Term__c> paymntTermMap = getPaymentTerm();

    if (paymntTermMap.containsKey(thisAccount.GTV_Payment_Term__c)) {
      paymentTerm = paymntTermMap.get(thisAccount.GTV_Payment_Term__c).eid__c;
    } else {
      if (paymntTermMap.containsKey('Net 30')) {
        paymentTerm = paymntTermMap.get('Net 30').eid__c;
      } else {
        return 'Please select a Payment Term';
      }
    }
    string currencyType;
    TRACT_Bill_Cycle__c billCycle;
    List<TRACT_Bill_Cycle__c> billCycleList = [
      SELECT
        id,
        Eid__c,
        Name,
        Bill_Cycle_Type__c,
        TRACT_Bill_Cycle_Currency_Type__c
      FROM TRACT_Bill_Cycle__c
      WHERE Name = :thisAccount.GTV_Bill_Cycle__c
      LIMIT 1
    ];
    if (billCycleList.size() > 0) {
      billCycle = billCycleList[0];
    } else {
      error = 'Please select the Bill Cycle.';
      return error;
    }
    if (null == billCycle) {
      return 'Bill Cycle does not exist with the Country.';
    }
    String billingAccountString;
    APIDataService dataService = GTVDataService.getService();
    try {
      dataService.BillingAccountCreationMapping(
        thisAccountList,
        billCycle,
        bACEid,
        paymentTerm,
        tract.Mapped_Custom_Field_Id__c
      );
    } catch (Exception exp) {
      string errorMessage;
      string exMessage = ' ' + exp.getMessage();
      if (exMessage.contains('Unexpected element')) {
        errorMessage = 'The TRACT Login UserId & Password is incorrect! Please Verify the input and try again.';
      } else if (exMessage.contains('WebService returned a SOAP Fault')) {
        errorMessage = exMessage.substring(
          exMessage.indexOf('WebService returned a SOAP Fault:') + 33,
          exMessage.indexOf('faultcode')
        );
      } else if (exMessage.contains('Validation Error:')) {
        errorMessage = exMessage.substringAfterLast('Validation Error:');
      } else if (exMessage.contains('IO Exception')) {
        errorMessage =
          'The TRACT URL is incorrect. ' +
          exMessage.substring(exMessage.indexOf('IO Exception') + 13);
      } else if (exMessage.contains('ApiException:')) {
        errorMessage = exMessage.substringAfterLast('Validation error:');
      } else {
        errorMessage = 'TRACT Server ' + exMessage;
      }
      error = errorMessage;
      thisAccount.status__c = 'Error Occurred';
      if (
        TRACTAPIUtil.checkFieldLevelSecurity('Account', 'status__c', 'Update')
      ) {
        update thisAccount;
      }
    }
    return error;
  }
  /**
   *Method to get payment term.
   *@return paymentTermMap [key:paymentTerm Name , value:paymentTerm]
   */

  public static map<String, Payment_Term__c> getPaymentTerm() {
    list<Payment_Term__c> paymentTermList = [
      SELECT Name, eid__c
      FROM Payment_Term__c
      LIMIT 1000
    ];
    map<String, Payment_Term__c> paymentTermMap = new Map<String, Payment_Term__c>();
    for (Payment_Term__c p : paymentTermList) {
      paymentTermMap.put(p.Name, p);
    }
    return paymentTermMap;
  }
}