src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tract_Billing_Account__c</fullName>
        <label>Gotransverse Billing Account #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>agreementEndAction__c</fullName>
        <label>Gotransverse AgreementEndAction</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxServiceResources__c</fullName>
        <label>Gotransverse MaxServiceResources</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>minServiceResources__c</fullName>
        <label>Gotransverse MinServiceResources</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Service_Resource__c</fullName>
        <description>Please enter the New Service Identifier to be created while placing the Salesorder.</description>
        <inlineHelpText>Please enter the New Service Identifier to be created while placing the Salesorder.</inlineHelpText>
        <label>Gotransverse New Service Resource</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>overrideAgreementEndDate__c</fullName>
        <description>Override Agreement End Date</description>
        <label>Gotransverse Override Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>productEid__c</fullName>
        <description>The eid of Tract Product.</description>
        <label>Gotransverse Product Eid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurringProductPriceEid__c</fullName>
        <label>Gotransverse RecurringProductPriceEid</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gotransverse Service Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Service_Resource__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Please select an active Service Resource</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Resource__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxServiceResources__c</fullName>
        <label>Gotransverse Max Service Resources</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>minServiceResources__c</fullName>
        <label>Gotransverse Min Service Resources</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Information__c</fullName>
        <label>Gotransverse Product Price Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Service_Resource__c.object
<CustomObject>
    <description>TRACT Service Resource is required for Products.</description>
    <label>Service Resource</label>
    <nameField>
        <label>Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/TRACT_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to save the Gotransverse Configuration details.</description>
    <label>Gotransverse Setup</label>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Gotransverse Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Api_Version__c</fullName>
        <label>Gotransverse Api Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TractSFDC_Util_Test.cls
/**
 * Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
 * This software contains confidential and trade secret information of:
 * Transverse, LLC.
 * 620 Congress Ave.
 * Suite 200
 * Austin, TX 78701
 * USA
 * Use, duplication or disclosure of this software is prohibited
 * without prior written permission of Transverse, LLC.
 */

/**
 * This class is a test class of TractSFDC_Util class.
 * @author Aman Jain
 */

@isTest
private class TractSFDC_Util_Test {
  static testMethod void myUnitTest() {
    TRACT_Setup__c tract = HelperClass.getTract();
    tract.Active__c = true;
    tract.Api_Version__c = '30';
    system.assert(tract != null);
    insert tract;

    Service_Resource__c serviceResource = HelperClass.getServiceresource();
    system.assert(serviceResource != null);
    insert serviceResource;

    Opportunity opportunity = HelperClass.getOpportunity();
    //opportunity.eid__c = '12345';
    system.assert(opportunity != null);
    insert opportunity;

    Product2 product = HelperClass.getProduct2();
    product.eid__c = '12345';
    product.ProductCode = 'TRACT_SUBSCRIPTION';
    product.minServiceResources__c = 10;
    product.maxServiceResources__c = 10;
    system.assert(product != null);
    insert product;

    List<ProductPriceWrapper> ppList = new List<ProductPriceWrapper>();
    ProductPriceWrapper pp = new ProductPriceWrapper();
    pp.priceType = 'Recurring';
    pp.eid = '2342';
    pp.thruDate = system.today();
    pp.currencyType = 'EUR';
    pp.priceListEid = '2732';
    pp.recurrencePeriod = 'Month';
    pp.scheduledCharges = false;
    pp.priceOverride = false;

    ProductPriceRangeWrapper priceRange = new ProductPriceRangeWrapper();
    PriceRange.price = 20;
    PriceRange.quantityBeginRange = 1;
    PriceRange.quantityEndRange = 20;
    List<ProductPriceRangeWrapper> priceRangeList = new List<ProductPriceRangeWrapper>();
    PriceRangeList.add(PriceRange);
    pp.priceRangesList = PriceRangeList;
    ppList.add(pp);

    ProductPriceWrapper pp2 = new ProductPriceWrapper();
    pp2.priceType = 'OneTime';
    pp2.eid = '2342';
    pp2.thruDate = system.today();
    pp2.currencyType = 'EUR';
    pp2.priceListEid = '2732';
    pp2.recurrencePeriod = 'Month';
    pp2.scheduledCharges = false;
    pp2.priceOverride = false;

    pp2.priceRangesList = PriceRangeList;
    ppList.add(pp2);

    product.Price_Information__c = JSON.serialize(ppList);
    update product;

    OpportunityLineItem oppLineItem = HelperClass.getOpportunityLineItem();
    oppLineItem.Service_Resource__c = serviceResource.Id;
    oppLineItem.New_Service_Resource__c = 'newServiceResourec';
    oppLineItem.OpportunityId = opportunity.Id;
    oppLineItem.recurringProductPriceEid__c = '12345';
    oppLineItem.productEid__c = 12345;
    oppLineItem.agreementEndAction__c = 'EndAction';
    oppLineItem.overrideAgreementEndDate__c = Date.valueOf('2016-5-4');
    system.assert(oppLineItem != null);
    insert oppLineItem;

    String accountNum = '12345';
    Account account = HelperClass.getAccount();
    account.Tract_Billing_Account__c = accountNum;
    system.assert(account != null);
    insert account;

    String orderNum = '12206';
    String tractEid = '12345';
    Map<String, String> information = new Map<String, String>();
    information.put('OpportunityId', opportunity.Id);
    Decimal quantity = 5;
    String srIdentifierName = 'identifire';
    String decryptedStr = '12345';
    String input = 'ravi,kant,maurya';
    String separator = ',';
    string milestoneDate = String.valueOf(Date.today());
    DateTime productPriceDate = Datetime.newInstance(1960, 2, 17);
    String currencyIsoCode = 'AUD';
    list<String> selectedString = new List<string>();
    selectedString.add('Test');
    Test.startTest();
    TractSFDC_Util.updateOpportunity(opportunity.Id, orderNum, accountnum);
    TractSFDC_Util.getProductFromOpportunity(information);
    TractSFDC_Util.isNull(decryptedStr);
    TractSFDC_Util.convertToCamelCase(input, separator);
    TractSFDC_Util.changeDateFormat(milestoneDate);
    TractSFDC_Util.productPriceFormat(productPriceDate);
    TractSFDC_Util.getCurrencySymbole(currencyIsoCode);
    TractSFDC_Util.getAdjustmentType('Test');
    TractSFDC_Util.getPhone('Test', 'test', 'test', 'test');
    TractSFDC_Util.getCountry('Test');
    TractSFDC_Util.getState('Test');
    TractSFDC_Util.convertInvoiceTypeToCamelCase('Test', 'Test');
    TractSFDC_Util.removePriceListFromProduct(selectedString, 'Test');
    TractSFDC_Util.getRecurrencePeriod('Test');
    TractSFDC_Util.getRandomNumberString();
    TractSFDC_Util.getServiceStatus('test');
    Test.stopTest();
  }
}