salesforce-classic-Feature-IN-955/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Agreement_Information__c</fullName>
        <label>Gotransverse Agreement Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>eid__c</fullName>
        <label>Gotransverse Eid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

salesforce-classic-Feature-IN-955/src/objects/TRACT_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to save the Gotransverse Configuration details.</description>
    <label>Gotransverse Setup</label>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Gotransverse Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Api_Version__c</fullName>
        <label>Gotransverse Api Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Triggered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field store if a batch is currently in progress.</description>
        <label>Batch Triggered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapped_Custom_Field_Id__c</fullName>
        <description>This field store the id of custom field selected by the user on billing tab.</description>
        <label>Mapped Custom Field Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderStatus__c</fullName>
        <label>Gotransverse OrderStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPassword__c</fullName>
        <label>Gotransverse TPassword</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRACT_URL2_0__c</fullName>
        <label>Gotransverse URL2.0</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TRACT_URL__c</fullName>
        <defaultValue>&quot;https://tract-qa.gotransverse.com&quot;</defaultValue>
        <description>TRACT Server URL</description>
        <inlineHelpText>Please provide a correct TRACT URL. Ex https://my.tractbilling.com</inlineHelpText>
        <label>Gotransverse URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tract_User_Name__c</fullName>
        <defaultValue>&quot;algo-sales&quot;</defaultValue>
        <label>Gotransverse User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X_API_Key__c</fullName>
        <description>This field is use to store the API key.</description>
        <label>X-API-Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/TractSetup__c.object
<CustomObject>
    <label>Gotransverse Setup</label>
    <nameField>
        <label>Gotransverse Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gotransverse Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Gotransverse Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Api_Version__c</fullName>
        <label>Gotransverse Api Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Triggered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field store if a batch is currently in progress.</description>
        <label>Batch Triggered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapped_Custom_Field_Id__c</fullName>
        <description>This field store the id of custom field selected by the user on billing tab.</description>
        <label>Mapped Custom Field Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderStatus__c</fullName>
        <label>Gotransverse OrderStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPassword__c</fullName>
        <label>Gotransverse TPassword</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRACT_URL2_0__c</fullName>
        <label>Gotransverse URL2.0</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TRACT_URL__c</fullName>
        <defaultValue>&quot;https://tract-qa.gotransverse.com&quot;</defaultValue>
        <description>TRACT Servere URL</description>
        <inlineHelpText>Please provide a correct TRACT URL. Ex https://my.tractbilling.com</inlineHelpText>
        <label>Gotransverse URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tract_User_Name__c</fullName>
        <defaultValue>&quot;algo-sales&quot;</defaultValue>
        <inlineHelpText>Enter a valid Tract server Username.</inlineHelpText>
        <label>Gotransverse User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X_API_Key__c</fullName>
        <description>This field is use to store the API key</description>
        <label>X-API-Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TractBatchSyncProductAgreements.cls
/**
 * Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
 * This software contains confidential and trade secret information of:
 * Transverse, LLC.
 * 620 Congress Ave.
 * Suite 200
 * Austin, TX 78701
 * USA
 * Use, duplication or disclosure of this software is prohibited
 * without prior written permission of Transverse, LLC.
 */

/**
 * This is a batch class to sync agreements from GTV to salesforce.
 * @author AMAN JAIN
 */

global with sharing class TractBatchSyncProductAgreements implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
  @deprecated
  global TractSetup__c tractConfig;
  public Tract_Setup__c tractSetup;
  public list<Product2> productListToUpdate;
  public APIDataService dataService;
  /**
   * @description: Contructor to intialize the class variables.
   */
  global TractBatchSyncProductAgreements() {
    productListToUpdate = new List<Product2>();
    dataService = GTVDataService.getService();
  }
  /**
   * @description: Contructor to intialize the class variables.
   * @param tractConfig configuration setting to configure data from tract.
   */
  @deprecated
  global TractBatchSyncProductAgreements(TractSetup__c tractConfig) {
    this.tractConfig = tractConfig;
    productListToUpdate = new List<Product2>();
  }
  /**
   * @description: Contructor to intialize the class variables.
   * @param tractConfig configuration setting to configure data from tract.
   */
  global TractBatchSyncProductAgreements(Tract_Setup__c tractConfig) {
    this.tractSetup = tractConfig;
  }
  /**
   * @description: start method to query product with there agreement information whether they have or not.
   * @return list of products
   */
  global Database.QueryLocator start(Database.BatchableContext bc) {
    String query = 'select Agreement_Information__c, eid__c, name, id  from Product2 where eid__c <> null';
    return Database.getQueryLocator(query);
  }
  /**
   * @description: execute method to update product list with there realted agreements.
   */
  global void execute(Database.BatchableContext bc, list<sObject> scope) {
    List<Product2> listOfProducts = (list<Product2>) scope;
    List<Product2> currentProductList = new List<Product2>();
    if (listOfProducts != null && !listOfProducts.isEmpty()) {
      currentProductList = dataService.getGTVAgreeements(listOfProducts);
      productListToUpdate.addAll(currentProductList);
    }
  }
  /**
   * @description: finish method to perform update dml to update product with there realted agreements.
   */
  global void finish(Database.BatchableContext bc) {
    if (null != productListToUpdate && !productListToUpdate.isEmpty()) {
      update productListToUpdate;
    }
    TRACT_Setup__c tract;
    list<TRACT_Setup__c> tractList = new List<TRACT_Setup__c>();
    /* Querying the TRACT Setup Object */
    tractList = [
      SELECT
        id,
        TPassword__c,
        Tract_User_Name__c,
        TRACT_URL__c,
        Api_Version__c,
        Active__c,
        TRACT_URL2_0__c,
        X_API_Key__c,
        OrderStatus__c,
        Mapped_Custom_Field_Id__c,
        Batch_Triggered__c
      FROM TRACT_Setup__c
      WHERE Active__c = TRUE
      LIMIT 1
    ];
    /* Checking if the TRACT Setup record exist */
    if (!tractList.IsEmpty()) {
      tract = tractList.get(0);
      tract.Batch_Triggered__c = false;
      if (
        TRACTAPIUtil.checkFieldLevelSecurity(
          'TRACT3__TRACT_Setup__c',
          'Batch_Triggered__c',
          'Update'
        )
      ) {
        update tract;
      }
    }
  }
}